<a href="https://colab.research.google.com/github/DannyKuvonchbek/ai_foundation/blob/main/studentsPerformance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("Student_Performance.csv")

In [9]:
print("dataset shape:", df.shape)

dataset shape: (10000, 6)

In [10]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [11]:
print("dataset columns:", df.columns.tolist())

dataset columns: ['Hours Studied', 'Previous Scores', 'Extracurricular Activities', 'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index']

In [12]:
df.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,6.530600,4.583300,55.224800
std,2.589309,17.343152,1.695863,2.867348,19.212558
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,9.000000,100.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [14]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [19]:
df_columns = df[['Hours Studied', 'Previous Scores', 'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index']]
print(df_columns.mean())

Hours Studied                        4.9929
Previous Scores                     69.4457
Sleep Hours                          6.5306
Sample Question Papers Practiced     4.5833
Performance Index                   55.2248
dtype: float64

In [20]:
df_columns = df[['Hours Studied', 'Previous Scores', 'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index']]
df_columns.min()

Hours Studied                        1.0
Previous Scores                     40.0
Sleep Hours                          4.0
Sample Question Papers Practiced     0.0
Performance Index                   10.0
dtype: float64

In [21]:
print(df_columns.max())

Hours Studied                         9.0
Previous Scores                      99.0
Sleep Hours                           9.0
Sample Question Papers Practiced      9.0
Performance Index                   100.0
dtype: float64

In [22]:
print(df_columns.corr())

                                  Hours Studied  Previous Scores  Sleep Hours  \
Hours Studied                          1.000000        -0.012390     0.001245
Previous Scores                       -0.012390         1.000000     0.005944
Sleep Hours                            0.001245         0.005944     1.000000
Sample Question Papers Practiced       0.017463         0.007888     0.003990
Performance Index                      0.373730         0.915189     0.048106

                                  Sample Question Papers Practiced  \
Hours Studied                                             0.017463
Previous Scores                                           0.007888
Sleep Hours                                               0.003990
Sample Question Papers Practiced                          1.000000
Performance Index                                         0.043268

                                  Performance Index
Hours Studied                              0.373730
Previous Scores                            0.915189
Sleep Hours                                0.048106
Sample Question Papers Practiced           0.043268
Performance Index                          1.000000

In [23]:
df_columns

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,9,1,91.0
1,4,82,4,2,65.0
2,8,51,7,2,45.0
3,5,52,5,2,36.0
4,7,75,8,5,66.0
...,...,...,...,...,...
9995,1,49,4,2,23.0
9996,7,64,8,5,58.0
9997,6,83,8,5,74.0
9998,9,97,7,0,95.0
9999,7,74,8,1,64.0

In [26]:
df['Performance Index']

0       91.0
1       65.0
2       45.0
3       36.0
4       66.0
        ...
9995    23.0
9996    58.0
9997    74.0
9998    95.0
9999    64.0
Name: Performance Index, Length: 10000, dtype: float64

In [29]:
df['passed'] = np.where(df['Performance Index'] > 90, True, False)

In [30]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index,passed
0,7,99,Yes,9,1,91.0,True
1,4,82,No,4,2,65.0,False
2,8,51,Yes,7,2,45.0,False
3,5,52,Yes,5,2,36.0,False
4,7,75,No,8,5,66.0,False
...,...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0,False
9996,7,64,Yes,8,5,58.0,False
9997,6,83,Yes,8,5,74.0,False
9998,9,97,Yes,7,0,95.0,True
9999,7,74,No,8,1,64.0,False

In [32]:
df.groupby('passed')['Hours Studied'].mean()

passed
False    4.920948
True     8.363636
Name: Hours Studied, dtype: float64

In [33]:
df['passed'].value_counts()

passed
False    9791
True      209
Name: count, dtype: int64

In [34]:
values = df_columns.values
print(values)

print(np.mean(values, axis=0))
print(np.std(values, axis=0))

z_values =( values - np.mean(values, axis=0)) / np.std(values, axis=0)
print(z_values)

[[ 7. 99.  9.  1. 91.]
 [ 4. 82.  4.  2. 65.]
 [ 8. 51.  7.  2. 45.]
 ...
 [ 6. 83.  8.  5. 74.]
 [ 9. 97.  7.  0. 95.]
 [ 7. 74.  8.  1. 64.]]
[ 4.9929 69.4457  6.5306  4.5833 55.2248]
[ 2.58917933 17.34228507  1.69577818  2.86720441 19.21159715]
[[ 0.77518771  1.70417565  1.45620461 -1.24975394  1.86216688]
 [-0.38348058  0.72391268 -1.49229423 -0.90098215  0.50881766]
 [ 1.16141048 -1.06362569  0.27680507 -0.90098215 -0.5322202 ]
 ...
 [ 0.38896495  0.7815752   0.86650484  0.1453332   0.9772847 ]
 [ 1.54763324  1.5888506   0.27680507 -1.59852572  2.07037446]
 [ 0.77518771  0.26261245  0.86650484 -1.24975394  0.45676577]]

In [36]:
top_scores = df[df['Performance Index'] > 90]
print(len(top_scores))

209